apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: estoque
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://inventory-db:5432/inventory_db
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: estoque
spec:
  selector:
    app: inventory
  ports:
    - port: 8082
      targetPort: 8082
